### ISSUE TITLE
Malf bot or AI

### ISSUE THREAD

**Issue by ByteSizedLaw** [optimumtact/tox-pkgs#1]
https://github.com/tgstation/tgstation/pull/87686#discussion_r1829977303

I'm not a bot and not AI, I'm also not joining any discords or appealing anything.
I find it highly ridiculous that I've been blocked for helping someone because you felt that I "look like a bot or AI".

Whether you unblock me or not, at least help the guy figure out why his builds are failing:
![image](https://github.com/user-attachments/assets/f0a70b6e-876d-48df-b941-5d55d542cc52)
![image](https://github.com/user-attachments/assets/6321f02c-da34-44a9-a5e9-0115cdaede7d)
![image](https://github.com/user-attachments/assets/6cefa70f-e168-43a5-b4c0-331556a8c834)

so far, I've narrowed the <code>Run linters</code> part down to a single line - which was what I was discussing with him before I got blocked
![image](https://github.com/user-attachments/assets/56eeaa80-600b-4a5c-ab58-d39561b2ba62)

he doesn't seem to be aware that they're failing though and will prevent his code from merging, so please help him
![image](https://github.com/user-attachments/assets/500f3cd4-c182-426e-b139-5798eb1ac0b0)

**Comment by optimumtact** [comment]
if you want to appeal your ban do it on discord. if you dont want to do that then cope

also, the build is not failing on that step, so if you're going to spam AI comments at least make sure they're correct.

Also I am helping them, which you would know, if you joined our discord.
